# -*- coding: utf-8 -*-
"""Graph_Generator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/130D1tPlPC_O3bSt5Nj-wt_U5Y3TsQ1_v
"""

from kcol_graph_gen import KColorableGraphGenerator
import random

class Vertex:
    def __init__(self, id):
        self.id = id
        self.distance = 0
        self.predecessor = None
        self.color=None
class Edge:
    def __init__(self, left_edge, right_edge, weight=0):
        self.left_edge = left_edge
        self.right_edge = right_edge
        self.weight = weight
class Graph:
    def __init__(self, vertices, edges):
        self.vertices = vertices
        self.edges = edges

import random
class KColorable_Graph_Generator:
 def __init__(self, seed=42, file_name="edged.txt"):
  self.seed = seed
  self.file_name = file_name

 def save_edges(self,Graph,weighted=False):
  try:
    with open(self.file_name, "w", encoding='ascii') as f:
      for edge in Graph.edges:
        if weighted:
          f.write(f"{edge.left_edge.id} {edge.weight} {edge.right_edge.id}\n")
        else:
          f.write(f"{edge.left_edge.id} {edge.right_edge.id}\n")
    print("Data successfully written to my_ascii_file.txt with ASCII encoding.")
  except UnicodeEncodeError as e:
    print(f"Error: Could not encode data to ASCII. Contains non-ASCII characters: {e}")

 def generate_online_kcolourable_graph(self, n, k,p=0.5):
   random.seed(self.seed)
   list_of_sets = []
   E = set()
   string_set_of_edges = set()

   for i in range(k):
      list_of_sets.append([])
   counter=0
   for i in range(n):
      vertex = Vertex(i)
      if counter <k:
        list_of_sets[counter].append(vertex)
        counter+=1
      else:
        rd_int = random.randint(0, (k-1))
        list_of_sets[rd_int].append(vertex)
   for vertex_set_i in list_of_sets:
      for vertex_v in vertex_set_i:
        for vertex_set_j in list_of_sets:
          if vertex_set_i!=vertex_set_j:
            # Add at least one edge between each vertex in Si to a vertex in Sj
            vertex_u = vertex_set_j[random.randint(0, len(vertex_set_j)-1)]
            str_e1=str(vertex_u.id)+","+str(vertex_v.id)
            str_e2=str(vertex_v.id)+","+str(vertex_u.id)
            # todo checker
            if str_e1 not in string_set_of_edges and str_e2 not in string_set_of_edges:
              string_set_of_edges.add(str_e1)
              string_set_of_edges.add(str_e2)
              e1 = Edge(vertex_u, vertex_v)
              e2 = Edge(vertex_v, vertex_u)
              E.add(e1)
              E.add(e2)

        for vertex_set_j in list_of_sets:
          if vertex_set_i!=vertex_set_j:
            for vertex_u in vertex_set_j:
              rand = random.random()
              if rand < p:
                str_e1=str(vertex_u.id)+","+str(vertex_v.id)
                str_e2=str(vertex_v.id)+","+str(vertex_u.id)
                if str_e1 not in string_set_of_edges and str_e2 not in string_set_of_edges:
                  string_set_of_edges.add(str_e1)
                  string_set_of_edges.add(str_e2)
                  e1 = Edge(vertex_u, vertex_v)
                  e2 = Edge(vertex_v, vertex_u)
                  E.add(e1)
                  E.add(e2)
   V = set()
   for vertex_set in list_of_sets:
        V.add(frozenset(vertex_set))
   graph = Graph(V, E)
   self.save_edges(graph)
   return graph

kcolorable_graph_generator = KColorable_Graph_Generator(26)
graph = kcolorable_graph_generator.generate_online_kcolourable_graph(6, 2, 0.95)